Repository JupiterOne/graph-jamf, pull requests merged in 2023-06, with the labels that each got.

#143 DEVICE-123 - Fetch more detailed mobile device information
  src/jamf/client.ts
  src/jamf/types.ts
  src/steps/devices/__snapshots__/converters.test.ts.snap
  src/steps/devices/converters.test.ts
  src/steps/devices/converters.ts
  src/steps/devices/index.ts
  test/mocks.ts
Labels: minor, release

#145 Do nothing so CI can republish this project
  .gitignore
Labels: patch, release

#147 NOTICKET - Add preversion hook to fix published package
  package.json
Labels: patch, release

#148 INT-8568/normalize-devices-os-versions
  src/steps/devices/converters.ts
  src/steps/devices/normalizer.test.ts
  src/steps/devices/normalizer.ts
Labels: bug, minor, release
